config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  get "/users", to: "users#index"
  get "/users/:user_id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index"
  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'post'
  post '/users/:user_id/posts/:id/', to: 'posts#create_comment'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'
  after_save :update_posts_counter
  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_comments
    comments.order('created_at desc').limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :update_allowed_parameters, if: :devise_controller?

  # prevent users to perform action without authentication
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.all.where(author_id: @user.id)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author = current_user
    redirect_to post_path if @comment.save
  end

  def create_like
    @like = Like.new(author: current_user, post: Post.find(params[:id]))
    redirect_to post_path if @like.save
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to posts_new_path
    flash[:success] = 'Post have been saved successfully'
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:user_id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsehafi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All posts <h1>

<div class="row">
<img class="profile-image" src="<%= @user.photo %>">
<strong><%= @user.name %></strong>
<p> <span>Number of posts: <%= @user.posts_counter %> </span></p>
</div>
<ul>
  <% @posts.each_with_index do |post, index| %>
  <li>

    <h3> Post #<%= index %></h3>
       <%= link_to "posts/#{post.id}" do%>
       <div class="row"><h3><%= post.text %></h3>
        <p>Comments <%= post.comments_counter %>, Likes <%= post.likes_counter %></p>
              </div>
       <%end%>
        <% post.recent_comments.each do |comment| %>
          <p>
            <%= User.find(comment.author_id).name %>: <%= comment.text %>
          </p>
        <% end %>
      </div>
    </div>
    </li>
  <% end %>
</ul>
<button>Pagination</button>

app/views/posts/new.html.erb
<div >
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: posts_new_path, method: :post, scope: :post do |f| %>
    <div class="column">
    <%= f.text_field :title, placeholder: 'Title of post' %>
    <%= f.text_area :text,placeholder: 'Description of post' %>
    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">
<h4><p>Post by <%= @user.name %></p></h4>
<p>Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter %></p>
</div>
<p><%= @post.text %></p>
        <% @post.comments.each do |comment| %>
          <p>
            <%= User.find(comment.author_id).name %>: <%= comment.text %>
          </p>
    <% end %>
</ul>
<%= form_with model: @comment, url: post_path, method: :post, scope: :comment do |f| %>
    <%= f.text_area :text, label: "Add Comment" %>
    <%= f.submit "Comment" %>
  <% end %>
  <%= form_with model: @like, url: like_path, method: :post do |f| %>
    <%= f.submit "Like", class: "btn btn-danger" %>
<% end %>

app/views/users/index.html.erb
<h1>All User</h1>

<div class="column">
<% @users.each do |user| %>
<%= link_to "users/#{user.id}" do %>
  <div class="row">
  <img class="profile-image" src="<%= user.photo %>" alt="User photo">
   <h1> <p><%= user.name %></p>  </h1>
  <p><span>Number of posts: <%= user.posts_counter %> </span></p>
  </div>
  <%end%>
<% end %>

<%= link_to create_post_path do %>
<button>create post</button>
<%end%>
</div>

app/views/users/show.html.erb
<div>
    <div class="row">
    <img  class="profile-image" src="<%= @user.photo %>" alt="User photo">
    <p><h1><%= @user.name %></h1> <span>Number of posts: <%= @user.posts_counter %> </span></p>
    </div>
    <p>Bio</p>
    <p class="center"><%= @user.bio %></p>

    <ul>
    <% @user.recent_posts.each_with_index  do |post, index| %>
      <div class="row">
      <li>
      <h3> Post #<%= index %></h3>
        <h4><p><%= post.title %></p></h4>
        <p><%= truncate(post.text, length: 50) %></p>
      </li>
      <p>Comments <%= post.comments_counter %>, Likes <%= post.likes_counter %></p>
      </div>
    <% end %>

    <%= link_to "#{@user.id}/posts" do%>
    <button>see all project</button>
    <%end%>

    </ul>
</div>